### ISSUE TITLE
FE will break on TYPO3 8.6.1 and realurl

### ISSUE THREAD

**Issue by gilbertsoft** [aimeos/aimeos-typo3-dist#6]
This is not an issue which directly can be assigned to aimeos-dist, it's generated by bootstrap_package. But since you are recommending realurl and depend on bootstrap_package, it could be a option to correct that in aimeos-dist. So everybody is able to use it with T3 8.6.1 next month :-)

Situation:
bootstrap_package defines 3 languages in page.10.dataProcessing.40.special.value (and popup....) but does not add this 3 languages to sys_languages. So DmitryDulepov\Realurl\Configuration\AutomaticConfigurator->addLanguages has no effect and will not add the required config by default. The FE breaks with an Exception: RealURL could not process "/index.php?id=1&L=2" because "L" parameter is invalid.

I'm supecting this will be fixed in the next bootstrap_package release for 8.6.1, but until then there are two possible fixes:
- adding the languages (en, de, da) to sys_languages
- deleting page.10.dataProcessing.40.special.value

Because Aimeos not realy uses this languages the second one is my prefered solution. 

As I see you add "lib.languages >" to ts setup but this has no effect since bootstrap_package 7. Instead add this two lines to ts setup:
page.10.dataProcessing.40.special.value >
popup.10.dataProcessing.40.special.value >

But then still a line with the English language remains in the FE. To remove this too add this line to ts constants:
page.theme.metasection.enable = 0

What do you think?

**Comment by gilbertsoft** [comment]
Here my new template:

Constants:
...
page.theme.breadcrumb = 0
page.theme.metasection.enable = 0

page.logo.file = fileadmin/aimeos_dist/logo.png
...


Setup:
...
page.cssInline {
    10 = TEXT
    10.value = .basket-mini {float:right;}
}

page.10.dataProcessing.40.special.value >
popup.10.dataProcessing.40.special.value >

**Comment by aimeos** [comment]
RealUrl is only a suggestion but no requirement so the default setup will be OK. Let's see if the bootstrap_package will fix this in the next version. If not, we can fix add a workaround on our side. The next aimeos_dist release will be earliest in 3-4 weeks because we've released the a version last Friday ...

**Comment by aimeos** [comment]
Your suggested TS settings to disable the inactive language links have been added to the new release.
The `page.theme.metasection.enable = 0` part has been omitted because it has no effect in TYPO3 8.7

**Comment by superscotty19** [comment]
the author of bootstrap_package has decided he knows what's best for editors and now not only is this thread more relevant than ever but other sites on the same T3 install are being affected. There *must* be a way to remove the dependency of bootstrap_package for aimeos

**Comment by aimeos** [comment]
OK, we will care about a page tree for TYPO3 8.7 and Aimeos 18.10

**Comment by superscotty19** [comment]
Thanks for the quick reply!
Update: If you go to Extension Manager > bootstrap_package > gear icon > there are options to disable the overrides (i.e. bring back image CE width/height, etc.). This solves the immediate problem affecting other sites, however it still makes templating tricky and I assume it spans both T3 8.x and 9.x because bootstrap_package is a dependency for both (right?). 
Ideally, it would be fantastic if Aimeos simply made bootstrap_package optional (for those who know what they're doing), and then those who need a quick template could have bootstrap_package + aimeos_dist.
